import { Pokemon } from "./pokemon";

export const POKEMONS: Pokemon[] = [
    new Pokemon(1, 'Bulbizarre', ['Plante', 'Poison'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png', new Date()),
    new Pokemon(2, 'Herbizarre', ['Plante', 'Poison'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png', new Date()),
    new Pokemon(3, 'Florizarre', ['Plante', 'Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png', new Date()),
    new Pokemon(4, 'Salamèche', ['Feu'], 28, 10, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png', new Date()),
    new Pokemon(5, 'Reptincel', ['Feu'], 30, 11, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png', new Date()),
    new Pokemon(6, 'Dracaufeu', ['Feu', 'Vol'], 35, 15, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png', new Date()),
    new Pokemon(7, 'Carapuce', ['Eau'], 25, 6, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png', new Date()),
    new Pokemon(8, 'Carabaffe', ['Eau'], 28, 9, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png', new Date()),
    new Pokemon(9, 'Tortank', ['Eau'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png', new Date()),
    new Pokemon(10, 'Chenipan', ['Insecte'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png', new Date()),
    new Pokemon(11, 'Chrysacier', ['Insecte'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png', new Date()),
    new Pokemon(12, 'Papilusion', ['Insecte', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png', new Date()),
    new Pokemon(13, 'Aspicot', ['Insecte', 'Poison'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png', new Date()),
    new Pokemon(14, 'Coconfort', ['Insecte', 'Poison'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png', new Date()),
    new Pokemon(15, 'Dardargnan', ['Insecte', 'Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png', new Date()),
    new Pokemon(16, 'Roucool', ['Normal', 'Vol'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png', new Date()),
    new Pokemon(17, 'Roucoups', ['Normal', 'Vol'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png', new Date()),
    new Pokemon(18, 'Roucarnage', ['Normal', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png', new Date()),
    new Pokemon(19, 'Rattata', ['Normal'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png', new Date()),
    new Pokemon(20, 'Rattatac', ['Normal'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png', new Date()),
    new Pokemon(21, 'Piafabec', ['Normal', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png', new Date()),
    new Pokemon(22, 'Rapasdepic', ['Normal', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/022.png', new Date()),
    new Pokemon(23, 'Abo', ['Poison'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png', new Date()),
    new Pokemon(24, 'Arbok', ['Poison'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/024.png', new Date()),
    new Pokemon(25, 'Pikachu', ['Electrik'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png', new Date()),
    new Pokemon(26, 'Raichu', ['Electrik'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/026.png', new Date()),
    new Pokemon(27, 'Sabelette', ['Sol'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png', new Date()),
    new Pokemon(28, 'Sablaireau', ['Sol'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/028.png', new Date()),
    new Pokemon(29, 'Nidoran♀', ['Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/029.png', new Date()),
    new Pokemon(30, 'Nidorina', ['Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png', new Date()),
    new Pokemon(31, 'Nidoqueen', ['Poison', 'Sol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png', new Date()),
    new Pokemon(32, 'Nidoran♂', ['Poison'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/032.png', new Date()),
    new Pokemon(33, 'Nidorino', ['Poison'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/033.png', new Date()),
    new Pokemon(34, 'Nidoking', ['Poison', 'Sol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png', new Date()),
    new Pokemon(35, 'Mélofée', ['Fée'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png', new Date()),
    new Pokemon(36, 'Mélodelfe', ['Fée'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/036.png', new Date()),
    new Pokemon(37, 'Goupix', ['Feu'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png', new Date()),
    new Pokemon(38, 'Feunard', ['Feu'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/038.png', new Date()),
    new Pokemon(39, 'Rondoudou', ['Normal', 'Psy'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png', new Date()),
    new Pokemon(40, 'Grodoudou', ['Normal', 'Psy'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/040.png', new Date()),
    new Pokemon(41, 'Nosferapti', ['Poison', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/041.png', new Date()),
    new Pokemon(42, 'Nosferalto', ['Poison', 'Vol'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/042.png', new Date()),
    new Pokemon(43, 'Mystherbe', ['Plante', 'Poison'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/043.png', new Date()),
    new Pokemon(44, 'Ortide', ['Plante', 'Poison'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/044.png', new Date()),
    new Pokemon(45, 'Rafflesia', ['Plante', 'Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png', new Date()),
    new Pokemon(46, 'Paras', ['Insecte', 'Plante'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/046.png', new Date()),
    new Pokemon(47, 'Parasect', ['Insecte', 'Plante'], 28, 8, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/047.png', new Date()),
    new Pokemon(48, 'Mimitoss', ['Insecte', 'Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/048.png', new Date()),
    new Pokemon(49, 'Aéromite', ['Insecte', 'Poison'], 30, 12, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/049.png', new Date()),
    new Pokemon(50, 'Taupiqueur', ['Sol'], 25, 5, 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/050.png', new Date()),
]
